---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: risingstack/alpine:3.3-v4.3.1-3.0.1
    tag: v1
run:
  path: sh
  args:
  - -exc
  - |
    npm install -g typescript
    make test
  dir: ""
inputs:
- name: processoutjs-git-master
  path: gopath/src/github.com/processout/processoutjs
