---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest
run:
  path: sh
  args:
  - -exc
  - |
    npm install -g typescript
    cd processoutjs-git-master
    make test
  dir: ""
inputs:
- name: processoutjs-git-master
