resources:
- name: processoutjs-git-master
  type: git
  source:
    branch: master
    uri: https://github.com/ProcessOut/processout.js.git

- name: processoutjs-git-pr
  type: pull-request
  source:
    repo: ProcessOut/processout.js


resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr


jobs:
- name: processoutjs-test
  plan:
  - get: processoutjs-git-master
    trigger: true
    params:
      submodules: none
  - task: tests
    file: processoutjs-git-master/ci/tasks/processoutjs-test.yml

- name: processoutjs-pull-request
  plan:
  - get: processoutjs-git-pr
    trigger: true
  - put: processoutjs-git-pr
    params:
      path: processoutjs-git-pr
      status: pending
  - task: tests
    file: processoutjs-git-master/ci/tasks/processoutjs-test.yml
  - put: processoutjs-git-pr
    params:
      path: processoutjs-git-pr
      status: success
